package ml2changliangs

const (
	FhKongZiFu     = ""
	FhKongGe       = " "
	FhBoLangHao    = "~"
	FhGanTanHao    = "!"
	FhJingHao      = "#"
	FhMeiYuanHao   = "$"
	FhBaiFenHao    = "%"
	FhChengFangHao = "^"
	FhQieHao       = "&"
	FhXingHao      = "*"
	FhXiaHuaXian   = "_"
	FhJiaHao       = "+"
	FhJianHao      = "-"
	FhDengHao      = "="

	FhZuoJianKuoHao  = "<"
	FhYouJianKuoHao  = ">"
	FhZuoXiaoKuoHao  = "("
	FhYouXiaoKuoHao  = ")"
	FhZuoZhongKuoHao = "["
	FhYouZhongKuoHao = "]"
	FhZuoDaKuoHao    = "{"
	FhYouDaKuoHao    = "}"
	FhShuXian        = "|"
	FhXieXian        = "/"
	FhFanXieXian     = "\\"
	FhMaoHao         = ":"
	FhFenHao         = ";"
	FhShuangYinHao   = "\""
	FhDanYinHao      = "'"
	FhDouHao         = ","
	FhDianHao        = "."
	FhWenHao         = "?"

	FhWenZiFu = "`"
)
